services:
  client:
    build:
      context: ./todo_client/todo_client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  
    volumes:
      - ./todo_client/todo_client:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    depends_on:
      - server
    command: npm run dev  

  server:
    build:
      context: ./todo_server/todo_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    volumes:
      - ./todo_server/todo_server:/app
      - /app/node_modules
    env_file:
      - ./todo_server/todo_server/.env
    depends_on:
      - db
    command: node index.js

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: todo_app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
